/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangTermsAndConditionsIndexRouteImport } from './routes/$lang/terms-and-conditions/index'
import { Route as LangSuccessStoryIndexRouteImport } from './routes/$lang/success-story/index'
import { Route as LangResourcesIndexRouteImport } from './routes/$lang/resources/index'
import { Route as LangProfileIndexRouteImport } from './routes/$lang/profile/index'
import { Route as LangPrivacyPolicyIndexRouteImport } from './routes/$lang/privacy-policy/index'
import { Route as LangOurPlansIndexRouteImport } from './routes/$lang/our-plans/index'
import { Route as LangLoginIndexRouteImport } from './routes/$lang/login/index'
import { Route as LangFreeMocksIndexRouteImport } from './routes/$lang/free-mocks/index'
import { Route as LangExamsIndexRouteImport } from './routes/$lang/exams/index'
import { Route as LangEditorialsCornerIndexRouteImport } from './routes/$lang/editorials-corner/index'
import { Route as LangCurrentAffairsIndexRouteImport } from './routes/$lang/current-affairs/index'
import { Route as LangCheckoutIndexRouteImport } from './routes/$lang/checkout/index'
import { Route as LangCancellationRefundIndexRouteImport } from './routes/$lang/cancellation-refund/index'
import { Route as LangAllExamsIndexRouteImport } from './routes/$lang/all-exams/index'
import { Route as LangAboutIndexRouteImport } from './routes/$lang/about/index'
import { Route as LangExamsExamCategoryIndexRouteImport } from './routes/$lang/exams/$examCategory/index'
import { Route as LangEditorialsCornerSlugIndexRouteImport } from './routes/$lang/editorials-corner/$slug/index'
import { Route as LangCurrentAffairsSlugIndexRouteImport } from './routes/$lang/current-affairs/$slug/index'
import { Route as LangExamsExamCategoryTestSlugIndexRouteImport } from './routes/$lang/exams/$examCategory/$testSlug/index'

const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangTermsAndConditionsIndexRoute =
  LangTermsAndConditionsIndexRouteImport.update({
    id: '/terms-and-conditions/',
    path: '/terms-and-conditions/',
    getParentRoute: () => LangRoute,
  } as any)
const LangSuccessStoryIndexRoute = LangSuccessStoryIndexRouteImport.update({
  id: '/success-story/',
  path: '/success-story/',
  getParentRoute: () => LangRoute,
} as any)
const LangResourcesIndexRoute = LangResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => LangRoute,
} as any)
const LangProfileIndexRoute = LangProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => LangRoute,
} as any)
const LangPrivacyPolicyIndexRoute = LangPrivacyPolicyIndexRouteImport.update({
  id: '/privacy-policy/',
  path: '/privacy-policy/',
  getParentRoute: () => LangRoute,
} as any)
const LangOurPlansIndexRoute = LangOurPlansIndexRouteImport.update({
  id: '/our-plans/',
  path: '/our-plans/',
  getParentRoute: () => LangRoute,
} as any)
const LangLoginIndexRoute = LangLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => LangRoute,
} as any)
const LangFreeMocksIndexRoute = LangFreeMocksIndexRouteImport.update({
  id: '/free-mocks/',
  path: '/free-mocks/',
  getParentRoute: () => LangRoute,
} as any)
const LangExamsIndexRoute = LangExamsIndexRouteImport.update({
  id: '/exams/',
  path: '/exams/',
  getParentRoute: () => LangRoute,
} as any)
const LangEditorialsCornerIndexRoute =
  LangEditorialsCornerIndexRouteImport.update({
    id: '/editorials-corner/',
    path: '/editorials-corner/',
    getParentRoute: () => LangRoute,
  } as any)
const LangCurrentAffairsIndexRoute = LangCurrentAffairsIndexRouteImport.update({
  id: '/current-affairs/',
  path: '/current-affairs/',
  getParentRoute: () => LangRoute,
} as any)
const LangCheckoutIndexRoute = LangCheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => LangRoute,
} as any)
const LangCancellationRefundIndexRoute =
  LangCancellationRefundIndexRouteImport.update({
    id: '/cancellation-refund/',
    path: '/cancellation-refund/',
    getParentRoute: () => LangRoute,
  } as any)
const LangAllExamsIndexRoute = LangAllExamsIndexRouteImport.update({
  id: '/all-exams/',
  path: '/all-exams/',
  getParentRoute: () => LangRoute,
} as any)
const LangAboutIndexRoute = LangAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => LangRoute,
} as any)
const LangExamsExamCategoryIndexRoute =
  LangExamsExamCategoryIndexRouteImport.update({
    id: '/exams/$examCategory/',
    path: '/exams/$examCategory/',
    getParentRoute: () => LangRoute,
  } as any)
const LangEditorialsCornerSlugIndexRoute =
  LangEditorialsCornerSlugIndexRouteImport.update({
    id: '/editorials-corner/$slug/',
    path: '/editorials-corner/$slug/',
    getParentRoute: () => LangRoute,
  } as any)
const LangCurrentAffairsSlugIndexRoute =
  LangCurrentAffairsSlugIndexRouteImport.update({
    id: '/current-affairs/$slug/',
    path: '/current-affairs/$slug/',
    getParentRoute: () => LangRoute,
  } as any)
const LangExamsExamCategoryTestSlugIndexRoute =
  LangExamsExamCategoryTestSlugIndexRouteImport.update({
    id: '/exams/$examCategory/$testSlug/',
    path: '/exams/$examCategory/$testSlug/',
    getParentRoute: () => LangRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/': typeof LangIndexRoute
  '/$lang/about': typeof LangAboutIndexRoute
  '/$lang/all-exams': typeof LangAllExamsIndexRoute
  '/$lang/cancellation-refund': typeof LangCancellationRefundIndexRoute
  '/$lang/checkout': typeof LangCheckoutIndexRoute
  '/$lang/current-affairs': typeof LangCurrentAffairsIndexRoute
  '/$lang/editorials-corner': typeof LangEditorialsCornerIndexRoute
  '/$lang/exams': typeof LangExamsIndexRoute
  '/$lang/free-mocks': typeof LangFreeMocksIndexRoute
  '/$lang/login': typeof LangLoginIndexRoute
  '/$lang/our-plans': typeof LangOurPlansIndexRoute
  '/$lang/privacy-policy': typeof LangPrivacyPolicyIndexRoute
  '/$lang/profile': typeof LangProfileIndexRoute
  '/$lang/resources': typeof LangResourcesIndexRoute
  '/$lang/success-story': typeof LangSuccessStoryIndexRoute
  '/$lang/terms-and-conditions': typeof LangTermsAndConditionsIndexRoute
  '/$lang/current-affairs/$slug': typeof LangCurrentAffairsSlugIndexRoute
  '/$lang/editorials-corner/$slug': typeof LangEditorialsCornerSlugIndexRoute
  '/$lang/exams/$examCategory': typeof LangExamsExamCategoryIndexRoute
  '/$lang/exams/$examCategory/$testSlug': typeof LangExamsExamCategoryTestSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/about': typeof LangAboutIndexRoute
  '/$lang/all-exams': typeof LangAllExamsIndexRoute
  '/$lang/cancellation-refund': typeof LangCancellationRefundIndexRoute
  '/$lang/checkout': typeof LangCheckoutIndexRoute
  '/$lang/current-affairs': typeof LangCurrentAffairsIndexRoute
  '/$lang/editorials-corner': typeof LangEditorialsCornerIndexRoute
  '/$lang/exams': typeof LangExamsIndexRoute
  '/$lang/free-mocks': typeof LangFreeMocksIndexRoute
  '/$lang/login': typeof LangLoginIndexRoute
  '/$lang/our-plans': typeof LangOurPlansIndexRoute
  '/$lang/privacy-policy': typeof LangPrivacyPolicyIndexRoute
  '/$lang/profile': typeof LangProfileIndexRoute
  '/$lang/resources': typeof LangResourcesIndexRoute
  '/$lang/success-story': typeof LangSuccessStoryIndexRoute
  '/$lang/terms-and-conditions': typeof LangTermsAndConditionsIndexRoute
  '/$lang/current-affairs/$slug': typeof LangCurrentAffairsSlugIndexRoute
  '/$lang/editorials-corner/$slug': typeof LangEditorialsCornerSlugIndexRoute
  '/$lang/exams/$examCategory': typeof LangExamsExamCategoryIndexRoute
  '/$lang/exams/$examCategory/$testSlug': typeof LangExamsExamCategoryTestSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/': typeof LangIndexRoute
  '/$lang/about/': typeof LangAboutIndexRoute
  '/$lang/all-exams/': typeof LangAllExamsIndexRoute
  '/$lang/cancellation-refund/': typeof LangCancellationRefundIndexRoute
  '/$lang/checkout/': typeof LangCheckoutIndexRoute
  '/$lang/current-affairs/': typeof LangCurrentAffairsIndexRoute
  '/$lang/editorials-corner/': typeof LangEditorialsCornerIndexRoute
  '/$lang/exams/': typeof LangExamsIndexRoute
  '/$lang/free-mocks/': typeof LangFreeMocksIndexRoute
  '/$lang/login/': typeof LangLoginIndexRoute
  '/$lang/our-plans/': typeof LangOurPlansIndexRoute
  '/$lang/privacy-policy/': typeof LangPrivacyPolicyIndexRoute
  '/$lang/profile/': typeof LangProfileIndexRoute
  '/$lang/resources/': typeof LangResourcesIndexRoute
  '/$lang/success-story/': typeof LangSuccessStoryIndexRoute
  '/$lang/terms-and-conditions/': typeof LangTermsAndConditionsIndexRoute
  '/$lang/current-affairs/$slug/': typeof LangCurrentAffairsSlugIndexRoute
  '/$lang/editorials-corner/$slug/': typeof LangEditorialsCornerSlugIndexRoute
  '/$lang/exams/$examCategory/': typeof LangExamsExamCategoryIndexRoute
  '/$lang/exams/$examCategory/$testSlug/': typeof LangExamsExamCategoryTestSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/'
    | '/$lang/about'
    | '/$lang/all-exams'
    | '/$lang/cancellation-refund'
    | '/$lang/checkout'
    | '/$lang/current-affairs'
    | '/$lang/editorials-corner'
    | '/$lang/exams'
    | '/$lang/free-mocks'
    | '/$lang/login'
    | '/$lang/our-plans'
    | '/$lang/privacy-policy'
    | '/$lang/profile'
    | '/$lang/resources'
    | '/$lang/success-story'
    | '/$lang/terms-and-conditions'
    | '/$lang/current-affairs/$slug'
    | '/$lang/editorials-corner/$slug'
    | '/$lang/exams/$examCategory'
    | '/$lang/exams/$examCategory/$testSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang'
    | '/$lang/about'
    | '/$lang/all-exams'
    | '/$lang/cancellation-refund'
    | '/$lang/checkout'
    | '/$lang/current-affairs'
    | '/$lang/editorials-corner'
    | '/$lang/exams'
    | '/$lang/free-mocks'
    | '/$lang/login'
    | '/$lang/our-plans'
    | '/$lang/privacy-policy'
    | '/$lang/profile'
    | '/$lang/resources'
    | '/$lang/success-story'
    | '/$lang/terms-and-conditions'
    | '/$lang/current-affairs/$slug'
    | '/$lang/editorials-corner/$slug'
    | '/$lang/exams/$examCategory'
    | '/$lang/exams/$examCategory/$testSlug'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/'
    | '/$lang/about/'
    | '/$lang/all-exams/'
    | '/$lang/cancellation-refund/'
    | '/$lang/checkout/'
    | '/$lang/current-affairs/'
    | '/$lang/editorials-corner/'
    | '/$lang/exams/'
    | '/$lang/free-mocks/'
    | '/$lang/login/'
    | '/$lang/our-plans/'
    | '/$lang/privacy-policy/'
    | '/$lang/profile/'
    | '/$lang/resources/'
    | '/$lang/success-story/'
    | '/$lang/terms-and-conditions/'
    | '/$lang/current-affairs/$slug/'
    | '/$lang/editorials-corner/$slug/'
    | '/$lang/exams/$examCategory/'
    | '/$lang/exams/$examCategory/$testSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/terms-and-conditions/': {
      id: '/$lang/terms-and-conditions/'
      path: '/terms-and-conditions'
      fullPath: '/$lang/terms-and-conditions'
      preLoaderRoute: typeof LangTermsAndConditionsIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/success-story/': {
      id: '/$lang/success-story/'
      path: '/success-story'
      fullPath: '/$lang/success-story'
      preLoaderRoute: typeof LangSuccessStoryIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/resources/': {
      id: '/$lang/resources/'
      path: '/resources'
      fullPath: '/$lang/resources'
      preLoaderRoute: typeof LangResourcesIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/profile/': {
      id: '/$lang/profile/'
      path: '/profile'
      fullPath: '/$lang/profile'
      preLoaderRoute: typeof LangProfileIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/privacy-policy/': {
      id: '/$lang/privacy-policy/'
      path: '/privacy-policy'
      fullPath: '/$lang/privacy-policy'
      preLoaderRoute: typeof LangPrivacyPolicyIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/our-plans/': {
      id: '/$lang/our-plans/'
      path: '/our-plans'
      fullPath: '/$lang/our-plans'
      preLoaderRoute: typeof LangOurPlansIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/login/': {
      id: '/$lang/login/'
      path: '/login'
      fullPath: '/$lang/login'
      preLoaderRoute: typeof LangLoginIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/free-mocks/': {
      id: '/$lang/free-mocks/'
      path: '/free-mocks'
      fullPath: '/$lang/free-mocks'
      preLoaderRoute: typeof LangFreeMocksIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/exams/': {
      id: '/$lang/exams/'
      path: '/exams'
      fullPath: '/$lang/exams'
      preLoaderRoute: typeof LangExamsIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/editorials-corner/': {
      id: '/$lang/editorials-corner/'
      path: '/editorials-corner'
      fullPath: '/$lang/editorials-corner'
      preLoaderRoute: typeof LangEditorialsCornerIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/current-affairs/': {
      id: '/$lang/current-affairs/'
      path: '/current-affairs'
      fullPath: '/$lang/current-affairs'
      preLoaderRoute: typeof LangCurrentAffairsIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/checkout/': {
      id: '/$lang/checkout/'
      path: '/checkout'
      fullPath: '/$lang/checkout'
      preLoaderRoute: typeof LangCheckoutIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/cancellation-refund/': {
      id: '/$lang/cancellation-refund/'
      path: '/cancellation-refund'
      fullPath: '/$lang/cancellation-refund'
      preLoaderRoute: typeof LangCancellationRefundIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/all-exams/': {
      id: '/$lang/all-exams/'
      path: '/all-exams'
      fullPath: '/$lang/all-exams'
      preLoaderRoute: typeof LangAllExamsIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/about/': {
      id: '/$lang/about/'
      path: '/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/exams/$examCategory/': {
      id: '/$lang/exams/$examCategory/'
      path: '/exams/$examCategory'
      fullPath: '/$lang/exams/$examCategory'
      preLoaderRoute: typeof LangExamsExamCategoryIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/editorials-corner/$slug/': {
      id: '/$lang/editorials-corner/$slug/'
      path: '/editorials-corner/$slug'
      fullPath: '/$lang/editorials-corner/$slug'
      preLoaderRoute: typeof LangEditorialsCornerSlugIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/current-affairs/$slug/': {
      id: '/$lang/current-affairs/$slug/'
      path: '/current-affairs/$slug'
      fullPath: '/$lang/current-affairs/$slug'
      preLoaderRoute: typeof LangCurrentAffairsSlugIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/exams/$examCategory/$testSlug/': {
      id: '/$lang/exams/$examCategory/$testSlug/'
      path: '/exams/$examCategory/$testSlug'
      fullPath: '/$lang/exams/$examCategory/$testSlug'
      preLoaderRoute: typeof LangExamsExamCategoryTestSlugIndexRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  LangIndexRoute: typeof LangIndexRoute
  LangAboutIndexRoute: typeof LangAboutIndexRoute
  LangAllExamsIndexRoute: typeof LangAllExamsIndexRoute
  LangCancellationRefundIndexRoute: typeof LangCancellationRefundIndexRoute
  LangCheckoutIndexRoute: typeof LangCheckoutIndexRoute
  LangCurrentAffairsIndexRoute: typeof LangCurrentAffairsIndexRoute
  LangEditorialsCornerIndexRoute: typeof LangEditorialsCornerIndexRoute
  LangExamsIndexRoute: typeof LangExamsIndexRoute
  LangFreeMocksIndexRoute: typeof LangFreeMocksIndexRoute
  LangLoginIndexRoute: typeof LangLoginIndexRoute
  LangOurPlansIndexRoute: typeof LangOurPlansIndexRoute
  LangPrivacyPolicyIndexRoute: typeof LangPrivacyPolicyIndexRoute
  LangProfileIndexRoute: typeof LangProfileIndexRoute
  LangResourcesIndexRoute: typeof LangResourcesIndexRoute
  LangSuccessStoryIndexRoute: typeof LangSuccessStoryIndexRoute
  LangTermsAndConditionsIndexRoute: typeof LangTermsAndConditionsIndexRoute
  LangCurrentAffairsSlugIndexRoute: typeof LangCurrentAffairsSlugIndexRoute
  LangEditorialsCornerSlugIndexRoute: typeof LangEditorialsCornerSlugIndexRoute
  LangExamsExamCategoryIndexRoute: typeof LangExamsExamCategoryIndexRoute
  LangExamsExamCategoryTestSlugIndexRoute: typeof LangExamsExamCategoryTestSlugIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangIndexRoute: LangIndexRoute,
  LangAboutIndexRoute: LangAboutIndexRoute,
  LangAllExamsIndexRoute: LangAllExamsIndexRoute,
  LangCancellationRefundIndexRoute: LangCancellationRefundIndexRoute,
  LangCheckoutIndexRoute: LangCheckoutIndexRoute,
  LangCurrentAffairsIndexRoute: LangCurrentAffairsIndexRoute,
  LangEditorialsCornerIndexRoute: LangEditorialsCornerIndexRoute,
  LangExamsIndexRoute: LangExamsIndexRoute,
  LangFreeMocksIndexRoute: LangFreeMocksIndexRoute,
  LangLoginIndexRoute: LangLoginIndexRoute,
  LangOurPlansIndexRoute: LangOurPlansIndexRoute,
  LangPrivacyPolicyIndexRoute: LangPrivacyPolicyIndexRoute,
  LangProfileIndexRoute: LangProfileIndexRoute,
  LangResourcesIndexRoute: LangResourcesIndexRoute,
  LangSuccessStoryIndexRoute: LangSuccessStoryIndexRoute,
  LangTermsAndConditionsIndexRoute: LangTermsAndConditionsIndexRoute,
  LangCurrentAffairsSlugIndexRoute: LangCurrentAffairsSlugIndexRoute,
  LangEditorialsCornerSlugIndexRoute: LangEditorialsCornerSlugIndexRoute,
  LangExamsExamCategoryIndexRoute: LangExamsExamCategoryIndexRoute,
  LangExamsExamCategoryTestSlugIndexRoute:
    LangExamsExamCategoryTestSlugIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
