/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuccessStoryIndexRouteImport } from './routes/success-story/index'
import { Route as ResourcesIndexRouteImport } from './routes/resources/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as OurPlansIndexRouteImport } from './routes/our-plans/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as FreeMocksIndexRouteImport } from './routes/free-mocks/index'
import { Route as ExamsIndexRouteImport } from './routes/exams/index'
import { Route as EditorialsCornerIndexRouteImport } from './routes/editorials-corner/index'
import { Route as CurrentAffairsIndexRouteImport } from './routes/current-affairs/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'

const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessStoryIndexRoute = SuccessStoryIndexRouteImport.update({
  id: '/success-story/',
  path: '/success-story/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const OurPlansIndexRoute = OurPlansIndexRouteImport.update({
  id: '/our-plans/',
  path: '/our-plans/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeMocksIndexRoute = FreeMocksIndexRouteImport.update({
  id: '/free-mocks/',
  path: '/free-mocks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsIndexRoute = ExamsIndexRouteImport.update({
  id: '/exams/',
  path: '/exams/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialsCornerIndexRoute = EditorialsCornerIndexRouteImport.update({
  id: '/editorials-corner/',
  path: '/editorials-corner/',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrentAffairsIndexRoute = CurrentAffairsIndexRouteImport.update({
  id: '/current-affairs/',
  path: '/current-affairs/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/': typeof LangIndexRoute
  '/current-affairs': typeof CurrentAffairsIndexRoute
  '/editorials-corner': typeof EditorialsCornerIndexRoute
  '/exams': typeof ExamsIndexRoute
  '/free-mocks': typeof FreeMocksIndexRoute
  '/login': typeof LoginIndexRoute
  '/our-plans': typeof OurPlansIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/success-story': typeof SuccessStoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang': typeof LangIndexRoute
  '/current-affairs': typeof CurrentAffairsIndexRoute
  '/editorials-corner': typeof EditorialsCornerIndexRoute
  '/exams': typeof ExamsIndexRoute
  '/free-mocks': typeof FreeMocksIndexRoute
  '/login': typeof LoginIndexRoute
  '/our-plans': typeof OurPlansIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/success-story': typeof SuccessStoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/': typeof LangIndexRoute
  '/current-affairs/': typeof CurrentAffairsIndexRoute
  '/editorials-corner/': typeof EditorialsCornerIndexRoute
  '/exams/': typeof ExamsIndexRoute
  '/free-mocks/': typeof FreeMocksIndexRoute
  '/login/': typeof LoginIndexRoute
  '/our-plans/': typeof OurPlansIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/success-story/': typeof SuccessStoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/'
    | '/current-affairs'
    | '/editorials-corner'
    | '/exams'
    | '/free-mocks'
    | '/login'
    | '/our-plans'
    | '/profile'
    | '/resources'
    | '/success-story'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang'
    | '/current-affairs'
    | '/editorials-corner'
    | '/exams'
    | '/free-mocks'
    | '/login'
    | '/our-plans'
    | '/profile'
    | '/resources'
    | '/success-story'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/'
    | '/current-affairs/'
    | '/editorials-corner/'
    | '/exams/'
    | '/free-mocks/'
    | '/login/'
    | '/our-plans/'
    | '/profile/'
    | '/resources/'
    | '/success-story/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  CurrentAffairsIndexRoute: typeof CurrentAffairsIndexRoute
  EditorialsCornerIndexRoute: typeof EditorialsCornerIndexRoute
  ExamsIndexRoute: typeof ExamsIndexRoute
  FreeMocksIndexRoute: typeof FreeMocksIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  OurPlansIndexRoute: typeof OurPlansIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  SuccessStoryIndexRoute: typeof SuccessStoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-story/': {
      id: '/success-story/'
      path: '/success-story'
      fullPath: '/success-story'
      preLoaderRoute: typeof SuccessStoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-plans/': {
      id: '/our-plans/'
      path: '/our-plans'
      fullPath: '/our-plans'
      preLoaderRoute: typeof OurPlansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-mocks/': {
      id: '/free-mocks/'
      path: '/free-mocks'
      fullPath: '/free-mocks'
      preLoaderRoute: typeof FreeMocksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/': {
      id: '/exams/'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorials-corner/': {
      id: '/editorials-corner/'
      path: '/editorials-corner'
      fullPath: '/editorials-corner'
      preLoaderRoute: typeof EditorialsCornerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/current-affairs/': {
      id: '/current-affairs/'
      path: '/current-affairs'
      fullPath: '/current-affairs'
      preLoaderRoute: typeof CurrentAffairsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  LangIndexRoute: typeof LangIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangIndexRoute: LangIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  CurrentAffairsIndexRoute: CurrentAffairsIndexRoute,
  EditorialsCornerIndexRoute: EditorialsCornerIndexRoute,
  ExamsIndexRoute: ExamsIndexRoute,
  FreeMocksIndexRoute: FreeMocksIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  OurPlansIndexRoute: OurPlansIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  SuccessStoryIndexRoute: SuccessStoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
