/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangSuccessStoryIndexRouteImport } from './routes/$lang/success-story/index'
import { Route as LangResourcesIndexRouteImport } from './routes/$lang/resources/index'
import { Route as LangProfileIndexRouteImport } from './routes/$lang/profile/index'
import { Route as LangOurPlansIndexRouteImport } from './routes/$lang/our-plans/index'
import { Route as LangLoginIndexRouteImport } from './routes/$lang/login/index'
import { Route as LangFreeMocksIndexRouteImport } from './routes/$lang/free-mocks/index'
import { Route as LangExamsIndexRouteImport } from './routes/$lang/exams/index'
import { Route as LangEditorialsCornerIndexRouteImport } from './routes/$lang/editorials-corner/index'
import { Route as LangCurrentAffairsIndexRouteImport } from './routes/$lang/current-affairs/index'

const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangSuccessStoryIndexRoute = LangSuccessStoryIndexRouteImport.update({
  id: '/success-story/',
  path: '/success-story/',
  getParentRoute: () => LangRoute,
} as any)
const LangResourcesIndexRoute = LangResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => LangRoute,
} as any)
const LangProfileIndexRoute = LangProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => LangRoute,
} as any)
const LangOurPlansIndexRoute = LangOurPlansIndexRouteImport.update({
  id: '/our-plans/',
  path: '/our-plans/',
  getParentRoute: () => LangRoute,
} as any)
const LangLoginIndexRoute = LangLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => LangRoute,
} as any)
const LangFreeMocksIndexRoute = LangFreeMocksIndexRouteImport.update({
  id: '/free-mocks/',
  path: '/free-mocks/',
  getParentRoute: () => LangRoute,
} as any)
const LangExamsIndexRoute = LangExamsIndexRouteImport.update({
  id: '/exams/',
  path: '/exams/',
  getParentRoute: () => LangRoute,
} as any)
const LangEditorialsCornerIndexRoute =
  LangEditorialsCornerIndexRouteImport.update({
    id: '/editorials-corner/',
    path: '/editorials-corner/',
    getParentRoute: () => LangRoute,
  } as any)
const LangCurrentAffairsIndexRoute = LangCurrentAffairsIndexRouteImport.update({
  id: '/current-affairs/',
  path: '/current-affairs/',
  getParentRoute: () => LangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/': typeof LangIndexRoute
  '/$lang/current-affairs': typeof LangCurrentAffairsIndexRoute
  '/$lang/editorials-corner': typeof LangEditorialsCornerIndexRoute
  '/$lang/exams': typeof LangExamsIndexRoute
  '/$lang/free-mocks': typeof LangFreeMocksIndexRoute
  '/$lang/login': typeof LangLoginIndexRoute
  '/$lang/our-plans': typeof LangOurPlansIndexRoute
  '/$lang/profile': typeof LangProfileIndexRoute
  '/$lang/resources': typeof LangResourcesIndexRoute
  '/$lang/success-story': typeof LangSuccessStoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/current-affairs': typeof LangCurrentAffairsIndexRoute
  '/$lang/editorials-corner': typeof LangEditorialsCornerIndexRoute
  '/$lang/exams': typeof LangExamsIndexRoute
  '/$lang/free-mocks': typeof LangFreeMocksIndexRoute
  '/$lang/login': typeof LangLoginIndexRoute
  '/$lang/our-plans': typeof LangOurPlansIndexRoute
  '/$lang/profile': typeof LangProfileIndexRoute
  '/$lang/resources': typeof LangResourcesIndexRoute
  '/$lang/success-story': typeof LangSuccessStoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/': typeof LangIndexRoute
  '/$lang/current-affairs/': typeof LangCurrentAffairsIndexRoute
  '/$lang/editorials-corner/': typeof LangEditorialsCornerIndexRoute
  '/$lang/exams/': typeof LangExamsIndexRoute
  '/$lang/free-mocks/': typeof LangFreeMocksIndexRoute
  '/$lang/login/': typeof LangLoginIndexRoute
  '/$lang/our-plans/': typeof LangOurPlansIndexRoute
  '/$lang/profile/': typeof LangProfileIndexRoute
  '/$lang/resources/': typeof LangResourcesIndexRoute
  '/$lang/success-story/': typeof LangSuccessStoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/'
    | '/$lang/current-affairs'
    | '/$lang/editorials-corner'
    | '/$lang/exams'
    | '/$lang/free-mocks'
    | '/$lang/login'
    | '/$lang/our-plans'
    | '/$lang/profile'
    | '/$lang/resources'
    | '/$lang/success-story'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang'
    | '/$lang/current-affairs'
    | '/$lang/editorials-corner'
    | '/$lang/exams'
    | '/$lang/free-mocks'
    | '/$lang/login'
    | '/$lang/our-plans'
    | '/$lang/profile'
    | '/$lang/resources'
    | '/$lang/success-story'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/'
    | '/$lang/current-affairs/'
    | '/$lang/editorials-corner/'
    | '/$lang/exams/'
    | '/$lang/free-mocks/'
    | '/$lang/login/'
    | '/$lang/our-plans/'
    | '/$lang/profile/'
    | '/$lang/resources/'
    | '/$lang/success-story/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/success-story/': {
      id: '/$lang/success-story/'
      path: '/success-story'
      fullPath: '/$lang/success-story'
      preLoaderRoute: typeof LangSuccessStoryIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/resources/': {
      id: '/$lang/resources/'
      path: '/resources'
      fullPath: '/$lang/resources'
      preLoaderRoute: typeof LangResourcesIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/profile/': {
      id: '/$lang/profile/'
      path: '/profile'
      fullPath: '/$lang/profile'
      preLoaderRoute: typeof LangProfileIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/our-plans/': {
      id: '/$lang/our-plans/'
      path: '/our-plans'
      fullPath: '/$lang/our-plans'
      preLoaderRoute: typeof LangOurPlansIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/login/': {
      id: '/$lang/login/'
      path: '/login'
      fullPath: '/$lang/login'
      preLoaderRoute: typeof LangLoginIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/free-mocks/': {
      id: '/$lang/free-mocks/'
      path: '/free-mocks'
      fullPath: '/$lang/free-mocks'
      preLoaderRoute: typeof LangFreeMocksIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/exams/': {
      id: '/$lang/exams/'
      path: '/exams'
      fullPath: '/$lang/exams'
      preLoaderRoute: typeof LangExamsIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/editorials-corner/': {
      id: '/$lang/editorials-corner/'
      path: '/editorials-corner'
      fullPath: '/$lang/editorials-corner'
      preLoaderRoute: typeof LangEditorialsCornerIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/current-affairs/': {
      id: '/$lang/current-affairs/'
      path: '/current-affairs'
      fullPath: '/$lang/current-affairs'
      preLoaderRoute: typeof LangCurrentAffairsIndexRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  LangIndexRoute: typeof LangIndexRoute
  LangCurrentAffairsIndexRoute: typeof LangCurrentAffairsIndexRoute
  LangEditorialsCornerIndexRoute: typeof LangEditorialsCornerIndexRoute
  LangExamsIndexRoute: typeof LangExamsIndexRoute
  LangFreeMocksIndexRoute: typeof LangFreeMocksIndexRoute
  LangLoginIndexRoute: typeof LangLoginIndexRoute
  LangOurPlansIndexRoute: typeof LangOurPlansIndexRoute
  LangProfileIndexRoute: typeof LangProfileIndexRoute
  LangResourcesIndexRoute: typeof LangResourcesIndexRoute
  LangSuccessStoryIndexRoute: typeof LangSuccessStoryIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangIndexRoute: LangIndexRoute,
  LangCurrentAffairsIndexRoute: LangCurrentAffairsIndexRoute,
  LangEditorialsCornerIndexRoute: LangEditorialsCornerIndexRoute,
  LangExamsIndexRoute: LangExamsIndexRoute,
  LangFreeMocksIndexRoute: LangFreeMocksIndexRoute,
  LangLoginIndexRoute: LangLoginIndexRoute,
  LangOurPlansIndexRoute: LangOurPlansIndexRoute,
  LangProfileIndexRoute: LangProfileIndexRoute,
  LangResourcesIndexRoute: LangResourcesIndexRoute,
  LangSuccessStoryIndexRoute: LangSuccessStoryIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
